openapi: 3.2.0
info:
  title: Lookup/ web service Ibis API
  version: '1.2'
  description: Common methods for searching for objects in the Lookup/Ibis database.
servers:
- url: https://lookup-test.srv.uis.cam.ac.uk/api/v1
  description: Test server
- url: https://www.lookup.cam.ac.uk/api/v1
  description: Live server
security:
- basicAuth: []
tags:
- name: ibis
  description: Common methods for searching for objects in the Lookup/Ibis database.
paths:
  /last-transaction:
    get:
      tags:
      - ibis
      summary: Get the ID of the last (most recent) transaction
      description: 'Get the ID of the last (most recent) transaction.


        A transaction represents an edit made to data in Lookup. Each

        transaction is assigned a unique, sequential, numeric ID. Thus

        this last transaction ID will increase each time some data in

        Lookup is changed.'
      operationId: Ibis_getLastTransactionId
      responses:
        200:
          description: The ID of the latest transaction.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      value:
                        type: integer
                        format: int64
                    description: 'Class representing the top-level container for all XML and JSON results.

                      This may be just a simple textual value or it may contain more complex

                      entities such as people, institutions, groups, attributes, etc.'
        default:
          $ref: '#/components/responses/ServerError'
  /version:
    get:
      tags:
      - ibis
      summary: Get the current API version number
      description: Get the current API version number.
      operationId: Ibis_getVersion
      responses:
        200:
          description: The API version number string.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      value:
                        type: string
                    description: 'Class representing the top-level container for all XML and JSON results.

                      This may be just a simple textual value or it may contain more complex

                      entities such as people, institutions, groups, attributes, etc.'
        default:
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
          description: The HTTP error status code.
        code:
          type: string
          description: A short textual description of the error status code.
        message:
          type: string
          description: A short textual description of the error message (typically one line).
        details:
          type: string
          description: The full details of the error (e.g., a Java stack trace).
      description: Class representing an error returned by the web service API.
  responses:
    ServerError:
      description: Unexpected error
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
                description: 'Class representing the top-level container for all XML and JSON results.

                  This may be just a simple textual value or it may contain more complex

                  entities such as people, institutions, groups, attributes, etc.'
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
externalDocs:
  description: More information
  url: https://www.lookup.cam.ac.uk/doc/ws-doc
